### ISSUE TITLE
Doesn't download for non-steam games

### ISSUE THREAD

**Issue by waldnercharles** [boppreh/steamgrid#10]
steamgrid does not detect any non-steam games.

**Comment by boppreh** [comment]
Hmm, this feature should be working since #6 . I'll look at it again.

**Comment by waldnercharles** [comment]
I tried dragging and dropping the steam installation folder as well, which also did not work.

**Comment by boppreh** [comment]
Strange, it's working correctly here. To help me debug this issue, please ensure that:

- you are using the [1.2 release](https://github.com/boppreh/steamgrid/releases/latest) (latest as of now), when support for non-Steam games was added
- the problem is only with non-steam games, and the others are downloaded correctly
- steamgrid ignored the game entirely, and not just failed to find a picture (it mentions in the report at the end if a picture wasn't found)
- you really did add the game to steam (kinda stupid, but sometimes we make mistakes)

**Comment by waldnercharles** [comment]
I am running on windows. Definitely using the 1.2 release. All other games are downloaded correctly. The number of games it shows is 186, whereas with non-steam games it should be around 250.

The report at the end does not mention that it fails. The games were added via https://github.com/scottrice/Ice - with the option to download images turned off.

Maybe the regex in AddNonSteamGames isn't finding anything.

**Comment by boppreh** [comment]
Thank you, that helps a lot. One last request before I go off to try and fix this: could you attach a copy of your `shortcuts.vdf` file, if you are okay with that? It should only contain the list of non-steam games, their paths and categories.

The file should be at `Steam\userdata\[your user id]\config\shortcuts.vdf`.

You are absolutely right, the problem is likely to be in the regex. I'm doing mostly a reverse-engineering job here, so please understand if the results are not as robust as we want.

**Comment by boppreh** [comment]
By the way, Ice is using [pysteam](https://github.com/scottrice/pysteam) to generate the `shortcuts.vdf`file. The source for that is found [here](https://github.com/scottrice/pysteam/blob/master/pysteam/_shortcut_generator.py).

**Comment by waldnercharles** [comment]
It looks like unfortunately github doesn't allow uploads of anything except images in the issue tracker, so here's a dropbox link to the `shortcuts.vdf`. https://www.dropbox.com/s/rpjzrah1bdt7i86/shortcuts.vdf?dl=0

**Comment by boppreh** [comment]
Thank you very much.

And funnily enough, pysteam is *also* [using a regex to parse the vdf file](https://github.com/scottrice/pysteam/blob/master/pysteam/_shortcut_parser.py#L50). I think I'm going to use their regex, it seems better than mine.

**Comment by boppreh** [comment]
I think I found the problem. `pysteam` is generating files with capitalized keys, like "Appname" and "Exe", while Steam doesn't. That was tripping up the regex. I don't know who is at fault here, but I added an "ignore case" flag on my side to ensure compatibility. As far as I can see that was the only discrepancy.

Could you try the [updated release](https://github.com/boppreh/steamgrid/releases/latest) and tell me if it fixes the your problem?

**Comment by waldnercharles** [comment]
Perfect. Great work on the fix, and obviously on the program.

**Comment by boppreh** [comment]
Thank you. If you find any other problems, feel free to open another issue.

I'm closing this one now.
