### ISSUE TITLE
Non-steam game gets skipped (not processed at all)

### ISSUE THREAD

**Issue by DinoMC** [boppreh/steamgrid#110]
I have 5 non-steam apps installed right now but when I run steamgrid it goes "Processing Firefox (1/4)", then goes through 4 and ends successfully, as if the 5th one didn't exist.

The missing one is the latest non steam game I added, manually, the exact same way as another one that does get processed. Any idea why this one gets skipped?

The one thing different for the skipped one is that it's installed on an SD card rather than the internal storage, could this be the issue?

PS. This is on Steamdeck, archlinux.

Edit : It appears to be linked to it being on the SD card, indeed. I tried copying the .exe to the /home folder and adding that as a non-steam game, and it works in that case.

Any idea how to have it work for games on the SD card too?

SD card folder is /run/media/mmcblk0p1 , game is in a sub folder 

Edit 2 : Added more games on SD card and they don't have this issue. It's just the one game that always get skipped. I guess it's no big deal, I'm just gonna set pictures manually for that game. Leaving this up in case you want more info.

**Comment by NightHammer1000** [comment]
Sometimes it skips new Shortcuts for me too.
The solution to this is was to Rename the Shortcut in Steam, Run steamgrid again and change the name back.

**Comment by aph3rson** [comment]
I'm also hitting the same issue. I've tried renaming the shortcut in question, but steamgrid refuses to pick up the shortcut. It's specifically showing a smaller number of shortcuts than I have in that file.

Could we perhaps get some more useful output in `addNonSteamGames()`, specifically inside the for loop for parsing games?

**Comment by NightHammer1000** [comment]
Yep. Run into that now too.
Added GOG Galaxy to my shortcuts and steamgrid just seems to ignore it for some Reason too. Not even Renaming works on that one.

**Comment by NightHammer1000** [comment]
By the looks of all the other open Issues, the Dev is no longer interrested in supporting this.
I will have a look at this when I have a bit of free time.

**Comment by NightHammer1000** [comment]
I recommend using BoilR
https://github.com/PhilipK/BoilR

Running it with all the Import Extensions disabled just pulls Images for Non-Steam Shortcuts.

**Comment by kmicki** [comment]
The shortcuts are skipped because for some reason unknown to me (I don't know go) the regex that parses the shortcut.vdf file doesn't work correctly. For me it produces 128 matches:

![image](https://user-images.githubusercontent.com/1463619/181018797-eda83331-8a89-4059-9f53-a3174f70e7f6.png)

But when I use the exact same regex pattern with Notepad++, it produces correct 146 matches:

![image](https://user-images.githubusercontent.com/1463619/181018958-9a21af8c-fd43-479b-932b-968c9784546e.png)

So it looks like it's something wrong with regex implementation in go.

**Comment by kmicki** [comment]
I just found out that it is because regexp in go matches Unicode text and when you try to match (.{4}) and, in my file, in this place there are bytes: `DB A1 82 9B' then `DB A1` is interpreted as a single Unicode character. To make it work properly regex matching would have to be forced not to use Unicode.
