### ISSUE TITLE
Overlay not working on some custom grids

### ISSUE THREAD

**Issue by tr0janman697** [boppreh/steamgrid#20]
First, thank you SO MUCH for your work on steamgrid.  It truly is one of the most helpful .exe's I have!

Now to the issue.  Some games, like Kelly Slater Pro Surfer or Ken Griffey Jr Slugfest for example, do not have proper 480x215 grids. The custom overlay via steamgrid  works as I could see it scale with the image in minuscule in size.  When I attempt to replace the Kelly Slater Pro Surfer grid with my own custom .jpg, steamgrid will replace it with the original pulled grid from the website.  Steamgrid will not replace most custom .png replacement but now it does not install the custom overlay :( 

The notification for "Steamgrid has replaced 0 images and applied (all) amount of overlays"  will pop up regardless if it has replaced an image on those specific type of games without proper grids and it could of replaced X amount of images, and not applied an overlay to those grids.

A similar issue happened to me with SUPERHOT.  Steamgrid finds the standard one and apply's the overlay.  Yet when I add a custom grid, steamgrid won't replace the custom grid but does not apply the overlay either. 

So to recap, steamgrid replaces certain games with custom images applied, and if it does not replace the custom image grid's it will certainly not apply an overlay on those specific games custom steam grids.

A majority of the games that I had applied custom steam grids worked properly so I thought it had to do with steamgrid replacing my custom grids when it sees a downloaded grid not at 460x215, but then SUPERHOT's overlay won't work either so I personally have no idea!  

I don't really know where my log's are located but I am willing to help in anyway I can to fix this issue, as the grids being replaced are the ones I need to get rid of the most.  I love having overlays as well and it is quite strange that only some of these don't want to work.  Here is to hoping we can fix this issue!

THANK YOU SO MUCH AGAIN FOR ALL YOUR HARD WORK!

**Comment by boppreh** [comment]
Thank you for the motivation. I've been a terrible maintainer the past few months, let's try to change it.

Currently the program does not apply overlays over existing custom images to avoid double-overlays and similar problems. This is hard to see because the images are tucked inside Steam's folder, and multiple copies are kept for backup. I now realize it needs to organize these images differently.

I'm working on a version that will store a canonical image for each game in a user accessible folder. Should fix your problem and make the process more transparent. Unfortunately I'll have to sacrifice the GUI for now, but it's just a progress bar and a dialog window.

More news soon.

**Comment by tr0janman697** [comment]
Whoa what a quick reply!  I tried to explained the issue as well as I could, it is such an odd intermediate one I thought it might be tough to explain.  I can imagine it can a bit rough when people give you the IT DOESN"T WORK rabble instead of trying to explain HOW it doesn't work.  

Thanks for your prompt assessment, really exciting stuff to hear an update is on the drawing board!

**Comment by boppreh** [comment]
I just released [v1.3.0](https://github.com/boppreh/steamgrid/releases/tag/v1.3.0). It fixes many problems, hopefully yours. It's not the transparent version I wanted, and it's now console instead of GUI, but the code is significantly better.

The replacement rules go like this:
- When Steamgrid processes a game it creates a copy in `userdata/USER/config/grid/gameid (original).jpg`.
- If there is a `gameid (original).jpg` image, it applies the overlay on that and discards `gameid.jpg` to avoid double-overlays.

`gameid.jpg` is what is created when you right-click "set custom image" on Steam itself.

In Steamgrid's logs `gameid (original).jpg` is called `backup` and finding only `gameid.jpg` is called `manual customization`. If you want to customize by hand again you have to navigate to that folder and remove the backup.

I find all this stupid and unnecessarily complex, but I don't have any better alternatives. Suggestions welcome.

It's now 3am and I'm going to sleep. Please report if it helps your problem or not, and thanks for the support.

**Comment by tr0janman697** [comment]
YOU ARE THE BEST!

The issue has been found and fixed! Steamgrid had the word (original) around all the ugly ones, once I deleted those grids in the /config/grid folder and added the (original) tag to my custom images, it works great!

Although for a game like Wakeboarding Unleashed we had some issues.  Steamgrid attempted to download a google image search and it came back with a different game grid.  When I removed the custom image and added my own, it still adds the overlay to the original google grid.  Only once I delete the google grid from the config/grid folder and put my grid in first via steam is when it will apply the overlay to the proper custom grid.

A GUI would be great, perhaps it could help get rid of the unwanted (original) grid's that started this request in the first place!

Once again, for the millionth time THANK YOU SO MUCH for getting this problem taken care of, I love steamgrid as much as Ice and SBP.  Keep up being an awesome dev and an important part of the community!

**Comment by boppreh** [comment]
It's been a pleasure.

Unfortunately the efforts required to maintain a GUI of this type would dwarf the program itself, so I'm leaving that for the distant future, or until someone sends a pull request.

I'm closing the issue now, but feel free to comment or reopen if you think it's needed.
