### ISSUE TITLE
SteamGrid crashes with over 1000 shortcuts

### ISSUE THREAD

**Issue by WeHaveFunHere** [boppreh/steamgrid#35]
SteamGrid worked well until I hit 1000 shortcuts and now SG will crash at the 100th processed shortcut no matter what.  I'd be happy to give you a log of the errors but SG shuts itself down instantly.

It seems the fix might have something to do with increasing that limit because SG still works for those first 100 shortcuts if it luckily picks one of the non overlayed grid's.  The second it hits the 101st game it has flashes a bunch of code and crashes lightning fast :(

I appreciate you looking into the matter, Thanks again for all your hard work!

**Comment by boppreh** [comment]
That sounds unusual. I would guess the problem is in one of the games, not the number of games per se. 

If you the program under Windows' code it should give the output in a readable way without closing the window. You can just drag and drop the binary into the prompt window and press enter. 

What system are you on, by the way? Windows or Linux? 

And thanks for the report.

**Comment by tr0janman697** [comment]
"runtime: out of memory: cannot allocate" is the main error I saw after taking a screenshot before SG crashed.  That ends up being the first line after the 103rd processed game no matter what.

[Here is a photo of a crashlog](http://imgur.com/a/22nyI), sorry I couldn't copy and paste it.
Thank you so much for the quick reply and I hope all is well in SteamGrid land!

**Comment by boppreh** [comment]
As a sanity test, I ran SG on my ~500 games and kept an eye on memory usage. It never went over 60 MB.

Since the stacktrace is all related to TLS and HTTP requests, my best guess it that it found something large while searching on Google. Does it always crash on the same game? Does it take visibly longer to process this game? Also, can you check your network usage during the period (ctrl+alt+del, performance tab), to see if it's really reading all this data, or if it's somehow compressed?

Thank you for your patience. This is a really unusual bug for a simple program in a garbage collected language...

**Comment by tr0janman697** [comment]
Good call to check the RAM usage, my steamgrid.exe process starts at about 245MB and works it's way up to 1GB then crashes.  Seems it is a memory leak!  The network usage seems a bit more in check with only 1MB being received and sent.

My SBP would look awful without all your hard work, I am happy to be able to help in anyway I can!

**Comment by boppreh** [comment]
I still haven't been able to reproduce this issue :(

If you are still experiencing it, please send me the full output of steamgrid, especially the name and ID of the game before the crash.

**Comment by WeHaveFunHere** [comment]
Congrats on the new version!  I am going to close the issue as it seems to have fixed itself after I deleted the contents of the /userdata/grid folder and let the new steamgrid re-do everything.  Thanks again for all your hard work!

**Comment by boppreh** [comment]
Most likely this was a page found via Google search, doing something funny and exploding the RAM usage. My guess is that the top result changed since then.

And thanks for taking your time to re-test it.
