### ISSUE TITLE
Revert back

### ISSUE THREAD

**Issue by xfechx** [boppreh/steamgrid#51]
How do we revert back to defaults and custom images I already had set up?

**Comment by boppreh** [comment]
Steamgrid only overwrites custom images to add overlays. You can delete the overlays folder and run it again to clear those images. The original, non-overlayed images are kept in `C:\Program Files (x86)\Steam\userdata\{STEAM_ID}\config\grid\originals`, with the hash of the overlayed image appended.

The program does not, however, keep track of which images were custom and which were downloaded afterwards.

**Comment by JonathanSchwob** [comment]
i think the revert feature may have broken with an update.

i've tried to revert by deleting the overlays folder and making sure it was eliminated from the trash bin, closed steam, run steamgrid, and the overlays are still there.

**Comment by Lucki** [comment]
That's actually surprisingly simple to fix:
https://github.com/boppreh/steamgrid/blob/eac4d3fef11a1f4bf6f85d1e6fc0ff089c5fcbd1/backup.go#L87-L96

~~~ patch
diff --git a/backup.go b/backup.go
index a39ae25..d37186f 100644
--- a/backup.go
+++ b/backup.go
@@ -88,8 +88,6 @@ func LoadExisting(overridePath string, gridDir string, game *Game, artStyleExten
        if err == nil && len(files) > 0 {
                err = loadImage(game, "manual customization", files[0])
                if err == nil {
-                       game.OverlayImageBytes = game.CleanImageBytes
-
                        // See if there exists a backup image with no overlays or modifications.
                        loadImage(game, "backup", getBackupPath(gridDir, game, artStyleExtensions))
                }
~~~

**Comment by justathoughtor2** [comment]
For the record, I encountered this bug as well. Since I don't have much experience with Go (and don't even have it installed on my PC right now), I just created a transparent image of dimensions 460x215 and saved it as the overlay for all impacted categories. Then a rerun of the program effectively "deleted" the overlay by simply making it transparent.

Until the fix from @Lucki is merged, perhaps you should provide an image of this sort so that users can revert if they want in the meantime.

![favorites](https://user-images.githubusercontent.com/1747037/68003892-c20bb180-fc45-11e9-88e1-246569a63479.png)
