### ISSUE TITLE
Any plans to support the upcoming library UI change for game boxart?

### ISSUE THREAD

**Issue by Revolt64** [boppreh/steamgrid#54]
https://www.tweaktown.com/news/66182/steams-new-ui-leaks-look-great/index.html

Steam is switching to standard boxart game images. Naturally, it's going to take ages to make these changes by hand.

It would be awesome if SteamGrid was updated to grab boxart instead of the current 460x215 images.

Thanks for all your hard work @boppreh

**Comment by PlayingKarrde** [comment]
The new grid came out today so this would most definitely be a welcome change. Currently most of my art is broken (even native games)

**Comment by ogierm** [comment]
Yup, would be nice!

**Comment by Lucki** [comment]
This fetches the new format instead of the old banner but I can't really recommend doing that. There are too many false positives from google. I've added "_cover_" to the search string but that doesn't help that much.

<details><summary>Screenshot</summary>

![Bildschirmfoto von 2019-09-20 17-57-32](https://user-images.githubusercontent.com/1408843/65341248-3297cb00-dbd0-11e9-968f-4493beadddfb.png)
</details><details><summary>Patch</summary>

~~~ diff
diff --git a/download.go b/download.go
index d18ecab..4aa09f4 100644
--- a/download.go
+++ b/download.go
@@ -14,7 +14,7 @@ import (
 // When all else fails, Google it. Uses the regular web interface. There are
 // two image search APIs, but one is deprecated and doesn't support exact size
 // matching, and the other requires an API key limited to 100 searches a day.
-const googleSearchFormat = `https://www.google.com.br/search?tbs=isz%3Aex%2Ciszw%3A460%2Ciszh%3A215&tbm=isch&num=5&q=`
+const googleSearchFormat = `https://www.google.com.br/search?tbs=isz%3Aex%2Ciszw%3A300%2Ciszh%3A450&tbm=isch&num=5&q=`
 
 // Possible Google result formats
 var googleSearchResultPatterns = []string{`imgurl=(.+?\.(jpeg|jpg|png))&amp;imgrefurl=`, `\"ou\":\"(.+?)\",\"`}
@@ -26,7 +26,7 @@ func getGoogleImage(gameName string) (string, error) {
 		return "", nil
 	}
 
-	url := googleSearchFormat + url.QueryEscape(gameName)
+	url := googleSearchFormat + url.QueryEscape(gameName) + `+cover`
 
 	client := &http.Client{}
 	req, err := http.NewRequest("GET", url, nil)
@@ -80,11 +80,11 @@ func tryDownload(url string) (*http.Response, error) {
 }
 
 // Primary URL for downloading grid images.
-const akamaiURLFormat = `https://steamcdn-a.akamaihd.net/steam/apps/%v/header.jpg`
+const akamaiURLFormat = `https://steamcdn-a.akamaihd.net/steam/apps/%v/library_600x900.jpg`
 
 // The subreddit mentions this as primary, but I've found Akamai to contain
 // more images and answer faster.
-const steamCdnURLFormat = `cdn.akamai.steamstatic.com/steam/apps/%v/header.jpg`
+const steamCdnURLFormat = `cdn.akamai.steamstatic.com/steam/apps/%v/library_600x900.jpg`
 
 // Tries to load the grid image for a game from a number of alternative
 // sources. Returns the final response received and a flag indicating if it was
@@ -148,10 +148,10 @@ func DownloadImage(gridDir string, game *Game) (bool, error) {
 }
 
 // Get game name from SteamDB as last resort.
-const steamDBForamt = `https://steamdb.info/app/%v`
+const steamDBFormat = `https://steamdb.info/app/%v`
 
 func GetGameName(gameId string) string {
-	response, err := tryDownload(fmt.Sprintf(steamDBForamt, gameId))
+	response, err := tryDownload(fmt.Sprintf(steamDBFormat, gameId))
 	if err != nil || response == nil {
 		return ""
 	}
diff --git a/steamgrid.go b/steamgrid.go
index 368b3f1..049f8c3 100644
--- a/steamgrid.go
+++ b/steamgrid.go
@@ -142,7 +142,10 @@ func startApplication() {
 			if err != nil {
 				errorAndExit(err)
 			}
-			imagePath := filepath.Join(gridDir, game.ID+game.ImageExt)
+			if game.ImageExt == `.jpeg` {
+				game.ImageExt = `.jpg`
+			}
+			imagePath := filepath.Join(gridDir, game.ID + `p` + game.ImageExt)
 			err = ioutil.WriteFile(imagePath, game.OverlayImageBytes, 0666)
 			if err != nil {
 				fmt.Printf("Failed to write image for %v because: %v\n", game.Name, err.Error())
~~~
</details>

**Comment by PoorPocketsMcNewHold** [comment]
SteamDB didn't tweaked their API for this new format change ? Might be better to request them to add a format parameter.

**Comment by Lucki** [comment]
Besides the missing api call for Steam**Grid**DB this program never fetched images from there. It's using steams image if available and searches google if it's missing and none is provided manually.

**Comment by Lucki** [comment]
@PoorPocketsMcNewHold SteamGridDB now supports the new format, I've added it to the PR.

**Comment by matrixraven** [comment]
> 
> 
> @PoorPocketsMcNewHold SteamGridDB now supports the new format, I've added it to the PR.

By the looks of the cobwebs around this repo, I'm not sure it's going to get merged. I pulled down your repo and switched to the new_cover branch, but I can't get go to build it. I don't know go, I'm just a n00b with it, but I googled some and can't seem to get it to work. Any chance you might build binaries from your own repo and post them there?

**Comment by Lucki** [comment]
> the cobwebs around this repo

The last activity was 2 months ago. Maybe @boppreh will look into his mails soon and see it.

> I can't get go to build it. I don't know go, I'm just a n00b with it

The PR isn't ready yet. It's still missing the new custom artwork and the scaling isn't ideal either. So this needs testing and reviews from experienced persons. If you know how the new names are set please comment in the PR.
If you're really into it this is what got me going:
1. `go get "golang.org/x/image/draw"`
2. `go build`


> Any chance you might build binaries from your own repo and post them there?

If it's ready I think about it but it's too soon.

**Comment by strzlee** [comment]
> > @PoorPocketsMcNewHold SteamGridDB now supports the new format, I've added it to the PR.
> 
> By the looks of the cobwebs around this repo, I'm not sure it's going to get merged. I pulled down your repo and switched to the new_cover branch, but I can't get go to build it. I don't know go, I'm just a n00b with it, but I googled some and can't seem to get it to work. Any chance you might build binaries from your own repo and post them there?

I uploaded a test build which should work with the new Steam UI here: [https://github.com/strzlee/steamgrid/releases](url)

**Comment by PoorPocketsMcNewHold** [comment]
> > > @PoorPocketsMcNewHold SteamGridDB now supports the new format, I've added it to the PR.
> > 
> > 
> > By the looks of the cobwebs around this repo, I'm not sure it's going to get merged. I pulled down your repo and switched to the new_cover branch, but I can't get go to build it. I don't know go, I'm just a n00b with it, but I googled some and can't seem to get it to work. Any chance you might build binaries from your own repo and post them there?
> 
> I uploaded a test build which should work with the new Steam UI here: [strzlee/steamgrid/releases](https://github.com/strzlee/steamgrid/releases)

Won’t be able to provide any feedback, since i’m on Linux. That the principal reason why I still use this steam grid app (apart from the other sources it takes), over the one they got at the SteamGridDB website.

**Comment by strzlee** [comment]
> > > > @PoorPocketsMcNewHold SteamGridDB now supports the new format, I've added it to the PR.
> > > 
> > > 
> > > By the looks of the cobwebs around this repo, I'm not sure it's going to get merged. I pulled down your repo and switched to the new_cover branch, but I can't get go to build it. I don't know go, I'm just a n00b with it, but I googled some and can't seem to get it to work. Any chance you might build binaries from your own repo and post them there?
> > 
> > 
> > I uploaded a test build which should work with the new Steam UI here: [strzlee/steamgrid/releases](https://github.com/strzlee/steamgrid/releases)
> 
> Won’t be able to provide any feedback, since i’m on Linux. That the principal reason why I still use this steam grid app (apart from the other sources it takes), over the one they got at the SteamGridDB website.

Linux build added: [https://github.com/strzlee/steamgrid/releases/tag/test-build-3.01](https://github.com/strzlee/steamgrid/releases/tag/test-build-3.01)

**Comment by PoorPocketsMcNewHold** [comment]
Thank you, @strzlee for your fast answer.
So, everything seems to work fine as you can see. It launches without any errors, and the auto steam folder detection works nicely.
I would recommend for that one, however, to empty the `/home/strzlee/.local/share/Steam/` placeholder as you can see from my previous attempts at launching it, without noticing that this wasn’t the supposed ¨own steam directory¨ that it found.
![Deepin Capture-écran_zone de sélection _20191110124354](https://user-images.githubusercontent.com/13170204/68543539-906ab700-03b8-11ea-9775-e7950ad01edb.png)
However, during the first run, it crashes with a runtime error. I’ll launch a second time and keep you updated with the results.
```Processing Tom Clancy's Ghost Recon Phantoms - EU: 100% XP\/AC Boost - 30 days (953/960)
Banner found from steam server
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x7b6ecd]

goroutine 235 [running]:
main.SteamGridDBGetRequest(0xc00002d220, 0x9d, 0xc0000b73b0, 0x20, 0x43, 0xc00002b3e0, 0x23, 0xc00002d220, 0x9d)
        /home/strzlee/go/src/github.com/strzlee/steamgrid/download.go:102 +0xad
main.getSteamGridDBImage(0xc0003d9b00, 0xc0002eec40, 0x7, 0x7, 0xc0000b73b0, 0x20, 0xc000023ac0, 0x8, 0x41, 0x4d, ...)
        /home/strzlee/go/src/github.com/strzlee/steamgrid/download.go:147 +0x3df
main.getImageAlternatives(0xc0003d9b00, 0x8e68d6, 0x5, 0xc0002eec40, 0x7, 0x7, 0x0, 0xc0000b73b0, 0x20, 0xc000023ac0, ...)
        /home/strzlee/go/src/github.com/strzlee/steamgrid/download.go:312 +0x38a
main.DownloadImage(0xc0002fc980, 0x37, 0xc0003d9b00, 0x8e68d6, 0x5, 0xc0002eec40, 0x7, 0x7, 0x0, 0xc0000b73b0, ...)
        /home/strzlee/go/src/github.com/strzlee/steamgrid/download.go:348 +0xe7
main.startApplication(0xc00156a8d3, 0x0, 0xc0000b73b0, 0x20, 0xc000023ac0, 0x8, 0xc0002ea3f0, 0x20, 0x0)
        /home/strzlee/go/src/github.com/strzlee/steamgrid/steamgrid.go:150 +0x1bb4
main.main.func4()
        /home/strzlee/go/src/github.com/strzlee/steamgrid/main.go:101 +0x1cb
fyne.io/fyne/widget.(*Button).Tapped(0xc0002ee540, 0xc0015f82e0)
        /home/strzlee/go/src/fyne.io/fyne/widget/button.go:210 +0x3d
created by fyne.io/fyne/internal/driver/gl.(*window).mouseClicked
        /home/strzlee/go/src/fyne.io/fyne/internal/driver/gl/window.go:635 +0x673```

**Comment by strzlee** [comment]
@PoorPocketsMcNewHold Thanks for testing, I'll have a look at that... 

meanwhile you can try this updated build: [https://github.com/strzlee/steamgrid/releases/tag/test-build](https://github.com/strzlee/steamgrid/releases/tag/test-build)

**Comment by PoorPocketsMcNewHold** [comment]
So, the updated ¨default¨ selection for the UI work well, nothing in the Steam path, default selection for the SteamGridDB artstyle set on alternate, and the added APNG selection, to static.
Despite all that, still same issues obviously.

**Comment by strzlee** [comment]
> So, the updated ¨default¨ selection for the UI work well, nothing in the Steam path, default selection for the SteamGridDB artstyle set on alternate, and the added APNG selection, to static.
> Despite all that, still same issues obviously.

I'm into it, but I think this is the wrong place to discuss bugs from an unfinished fork.
I'll message you for further informations.

**Comment by Michoko92** [comment]
Hi strzlee,
I tried your latest build (Windows), but it can't find the Steam folder. I tried to drop the Steam folder on the EXE file. I also edited the JSON file to put the Steam folder path there, but to no avail. Is there something I can do to make it work, please?

**Comment by strzlee** [comment]
> Hi strzlee,
> I tried your latest build (Windows), but it can't find the Steam folder. I tried to drop the Steam folder on the EXE file. I also edited the JSON file to put the Steam folder path there, but to no avail. Is there something I can do to make it work, please?

pls report problems here: [https://github.com/strzlee/steamgrid/issues](https://github.com/strzlee/steamgrid/issues)
