### ISSUE TITLE
Doesn't download logo images from steamgriddb

### ISSUE THREAD

**Issue by gibbawho** [boppreh/steamgrid#66]
I've noticed this script doesn't actually ever find any logo from steamgriddb even when there are clearly logo images for the game. I've also noticed their own manager app doesn't seem to find logo images either. Perhaps the steamgriddb api is broken for logos at the moment?

**Comment by Lucki** [comment]
The [called url](https://www.steamgriddb.com/api/v2/logos/steam/271590?styles=alternate&types=static&dimensions=1280x720) clearly gives me some results. A quick run also gives me some logos.

Please retest on your end.

**Comment by Giuliadilsa** [comment]
Hi, I also have the same issue, it just doesn't download logos

**Comment by Giuliadilsa** [comment]
I think maybe because we're using the latest release and it doesn't have the feature implemented yet, the "steamgrid now supports logos" commit was implemented december 28th, the latest release is from december 27th

And I can't figure out how to compile go

Please publish a new release if you got time

**Comment by Giuliadilsa** [comment]
Update: figured out how to use go, I compiled the last available source code and now it works, so I think that was the issue

**Comment by gibbawho** [comment]
Same. I built from the newest codebase and logos do in fact work. Thanks for the help.
