### ISSUE TITLE
[Feature Request] An option to run Steam Grid for a specific game

### ISSUE THREAD

**Issue by Ciriak** [boppreh/steamgrid#75]
Hello Amazing tool , very useful !

It would be nice to have an option where you specify a game by it's name or id and run SteamGrid only for it instead of running everything every time.

I have a very huge library and even with the cache , it take 3 - 4 minutes to run SteamGrid every time because it has to run throught every game.

Is that possible ?

**Comment by Lucki** [comment]
> Is that possible ?

It is!

Just …
1. … [add a command line argument which listens for something like `--appids`][1] …
1. … feed the appids to the `GetGames()` function [[1][2], [2][3]] …
2. … [and create a `map[string]*Game` of all appids when available instead of getting the normal user list][2].

[1]: https://github.com/boppreh/steamgrid/blob/master/steamgrid.go#L47-L60
[2]: https://github.com/boppreh/steamgrid/blob/master/games.go#L132-L144
[3]: https://github.com/boppreh/steamgrid/blob/master/steamgrid.go#L156
